branch-defaults:
  master:
    environment: TwitterWise-dev
environment-defaults:
  TwitterWise-dev:
    branch: null
    repository: null
global:
  application_name: TwitterWise
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/IIS 10.0 running
    on 64bit Windows Server 2016/1.2.0
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
